### ISSUE TITLE
Question about the memory map

### ISSUE THREAD

**Issue by hyf6661669** [sifive/freedom#101]
In SiFive FE310-G000 Manual v2p3, according to ```Table 3.1 FE310-G000 Memory Map```, the base address of Mask Rom is 0x0000_1000, and the base address of QSPI0 XIP is 0x2000_0000: 
![qq 20190119100533](https://user-images.githubusercontent.com/18757974/51420889-c6dd0880-1bd1-11e9-8c10-92825a64e12e.jpg)

But it seems that the reset value of ```pc``` in ```sifive.freedom.everywhere.e300artydevkit.E300ArtyDevKitConfig.v``` is 17'h1_0000, which I think should be 16'h1000. Besides, in freedom-e-sdk, the linker script for freedom-e300-arty (freedom-e-sdk/bsp/env/freedom-e300-arty/flash.lds) sets the start address of flash as 0x2040_0000, which I think should be 0x2000_0000:
![flash](https://user-images.githubusercontent.com/18757974/51420987-f3ddeb00-1bd2-11e9-932f-ce95da3d3037.jpg)

Does it means that the memory map of ```freedom-e300-arty``` is not the exactly the same as that of ```SiFive FE310-G000``` ??

**Comment by brucehoult** [comment]
I don't know about the 0x1000 vs 0x1_0000. The 0x1000 is definitely correct for the FE310, but I haven't used the Arty version.

0x2040_0000 is correct for linking the user program. The Flash starts at 0x2000_0000 and the OTP contains code that jumps to that address, but there is a small program that should be permanently loaded at 0x2000_0000. The main purpose of it is to have a short delay before jumping to the user program at 0x2040_0000 and look for the reset button being pressed, in which case it just loops instead.

The purpose of this is to allow the board to be recovered using OpenOCD/gdb via the USB interface if the user program does something really stupid such as turn off the clocks.

**Comment by hyf6661669** [comment]
@brucehoult 
Thanks for your fast reply.

Actually, in freedom/bootrom/xip/xip.S, the code is :
![image](https://user-images.githubusercontent.com/18757974/51421344-c6477080-1bd7-11e9-8541-a1a7fc3b1dda.png)
And in freedom/bootrom/xip/Makefile, the following command is used to generate the elf file from xip.S:
![image](https://user-images.githubusercontent.com/18757974/51421354-00187700-1bd8-11e9-9a90-e9ebcf200eb5.png)
It seems that nothing is written at 0x2000_0000 for ```freedom-e300-arty``` . But do you mean that some codes are written at 0x2000_0000 for ```FE310```, and we just don't need these codes when we are running ```freedom-e300-arty```?

Besides, it seems that the Top address of Mask Rom should be 0x0000_1FFF instead of 0x1000_1FFF:
![image](https://user-images.githubusercontent.com/18757974/51421384-86cd5400-1bd8-11e9-976b-cce7aa2f2dcf.png)

**Comment by brucehoult** [comment]
As I said, I have no idea how freedom-e300-arty is organised. I only know how the FE-310 and HiFive1 are organised. Maybe someone will come along with freedom-e300-arty experience.

On the HiFive1, the follow code is permanently loaded at 0x2000_0000 and the user's program is linked for 0x2040_0000:

https://github.com/sifive/freedom-e-sdk/blob/master/software/double_tap_dontboot/double_tap_dontboot.c

**Comment by hyf6661669** [comment]
The link is usefule, thank you!

**Comment by richardxia** [comment]
The latest freedom-e300-arty is configured slightly differently than the FE310-G000. Our newer designs, including the U540-C000, place the Mask ROM at 0x1_0000, which is what the HEAD of the master branch of this `freedom` repo sets it to. The latest version of the freedom-e310-arty .mcs file available on our website is from an older version of the codebase, where our memory map convention was to place the Mask ROM at 0x1000.

On the Arty configuration, although the SPI flash memory starts at address 0x2000_0000, the Arty board actually reserves the beginning of the flash memory to store the actual FPGA bitstream configuration, which allows the FPGA to automatically configure itself after being powered off and on. As a result, we cannot use the beginning of the flash memory to load user code, and we instead use address 0x2040_0000 to load user code.

**Comment by hyf6661669** [comment]
> The latest freedom-e300-arty is configured slightly differently than the FE310-G000. Our newer designs, including the U540-C000, place the Mask ROM at 0x1_0000, which is what the HEAD of the master branch of this `freedom` repo sets it to. The latest version of the freedom-e310-arty .mcs file available on our website is from an older version of the codebase, where our memory map convention was to place the Mask ROM at 0x1000.
> 
> On the Arty configuration, although the SPI flash memory starts at address 0x2000_0000, the Arty board actually reserves the beginning of the flash memory to store the actual FPGA bitstream configuration, which allows the FPGA to automatically configure itself after being powered off and on. As a result, we cannot use the beginning of the flash memory to load user code, and we instead use address 0x2040_0000 to load user code.

@richardxia 
Your answer is really clear, thanks a lot!!
