### ISSUE TITLE
Free vivado version sufficient ?

### ISSUE THREAD

**Issue by bagyavinoth** [sifive/freedom#122]
Hello,
I see that below vivado version is free of cost with limited functionalities.
Vivado Design Suite HL WebPACK

Is this sufficient to work with freedom platforms or do we need the paid version ?

Regards,
Vinoth

**Comment by erikdanie** [comment]
Yes, the free version should work fine to generate the freedom builds

**Comment by bagyavinoth** [comment]
Thanks for the response @erikdanie .
And i hope it's applicable to both the below platforms.
Freedom E300 Arty FPGA Dev Kit 
Freedom U500 VC707 FPGA Dev Kit
Right ?

Regards,
Vinoth

**Comment by richardxia** [comment]
Unfortunately, it only applies to the Arty boards. The VC707 requires a paid version of Vivado; however, the purchase of a VC707 board will come with a node-locked license of Vivado that can be used to synthesize bitstreams for the board.

**Comment by bagyavinoth** [comment]
Ho ok. Thanks @richardxia.
