### ISSUE TITLE
System clock

### ISSUE THREAD

**Issue by MarcoGeuna** [sifive/freedom#13]
Hi,

I'm trying to modify your U500 platform. In particular, my aim is to get the system clock not from the PCIe (I don't have this device), but deriving it from the MIG output clock.

My question is: which clock frequency do you give to the system? I mean the one of the  `top_clock` signal, inside the _U500VC707DevKitTop_ component.

Thank you so much!

**Comment by terpstra** [comment]
62.5MHz.

**Comment by MarcoGeuna** [comment]
Thanks! That was really useful! :-)
