### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by RISCVevaluation** [sifive/freedom#24]
Hi when I am trying to execute make -f Makefile.e300artydevkit mcs targets in Freedom E 310, i am getting the following error how to i am resolve this issue..... 

# export_ip_user_files -of_objects $obj -no_script -force
invalid command name "export_ip_user_files"
    while executing
"export_ip_user_files -of_objects $obj -no_script -force"
    (file "script/init.tcl" line 36)
INFO: [Common 17-206] Exiting Vivado at Thu May 12 10:42:37 2016...
make[1]: *** [obj/system.bit] Error 1

**Comment by richardxia** [comment]
Hi, what version of Vivado do you have installed?

**Comment by riscveval** [comment]
Hi, I am using Vivado 2015.1.

**Comment by richardxia** [comment]
Vivado 2015.1 doesn't appear to support the `export_ip_user_files` command. Please upgrade to a newer version of Vivado (the WebPACK edition is free and supports the Arty board).
