### ISSUE TITLE
The board_part definition was not found for digilentinc.com:arty:part0:1.1

### ISSUE THREAD

**Issue by Pengnian** [sifive/freedom#29]
hi,all

cd  freedom/fpga/e300artydevkit
make 

![freedom_error](https://user-images.githubusercontent.com/26727603/27629736-e0301754-5c25-11e7-84a2-4686b8f64e41.png)

**Comment by mwachs5** [comment]
You need to install the board part for the Arty board. There are instructions here on Digilent's website: https://reference.digilentinc.com/reference/software/vivado/board-files

**Comment by Pengnian** [comment]
@mwachs5  Thank you very much, I met a trouble again ! As a  beginner, Thanks your patience!
![also](https://user-images.githubusercontent.com/26727603/27645567-f7edad38-5c58-11e7-89ee-dcc90c4a9ea3.png)

**Comment by Pengnian** [comment]
@mwachs5 
![default](https://user-images.githubusercontent.com/26727603/27645885-de8432a8-5c59-11e7-8ad0-218bbb458113.png)

**Comment by richardxia** [comment]
It looks like the `VSRC_TOP` environment variable isn't getting set for some reason. Can you post the first few lines of console output immediately after you run `make -f Makefile.e300artydevkit mcs`, but before Vivado starts running?

**Comment by Pengnian** [comment]
@richardxia  Hi Richard,

when I  run  `make -f Makefile.e300artydevkit mcs`, doesn't work also!
![mcs](https://user-images.githubusercontent.com/26727603/27666402-04bb5234-5ca6-11e7-8ef3-4a177feb1651.png)

**Comment by mwachs5** [comment]
This second error looks the same as your other issue #28. Please check the version of scala you are using, it seems you are using a very old version.

**Comment by Pengnian** [comment]
@mwachs5 Okay,Thanks your remind !
