### ISSUE TITLE
use "freedom-e-sdk" to upload and debug my programs,but met some errors.

### ISSUE THREAD

**Issue by Pengnian** [sifive/freedom#30]
Hi,all 
I'm use command `make upload PROGRAM=hello BOARD=freedom-e300-arty` in the `freedon-e-sdk `directory. so,you can tell  me   the why?
![111](https://user-images.githubusercontent.com/26727603/27991454-0639051e-64aa-11e7-8f7a-e8e567d09513.png)

**Comment by mwachs5** [comment]
Please check your wiring connections to the debugger. It looks like you may have swapped or missing some connections.

**Comment by Pengnian** [comment]
@mwachs5 Thank you, the LED of debugger is light when connection between board and computer .
But when I use command `make upload PROGRAM=hello BOARD=freedom-e300-arty`,the led not bright ! But every time the errors maybe difference! 
![jtag](https://user-images.githubusercontent.com/26727603/28059380-aea4c5a0-6656-11e7-9071-a8ed86c9b134.png)

**Comment by mwachs5** [comment]
What FPGA image are you using? The message is telling you the JTAG ID is 0x20000001, which sounds like the Coreplex IP eval kit, not the Freedom E300 Arty Dev Kit. You should use BOARD=coreplexip-... to match

**Comment by Pengnian** [comment]
@mwachs5  Thank you very much !

**Comment by Pengnian** [comment]
@mwachs5 
![wires](https://user-images.githubusercontent.com/26727603/28360910-7cd086dc-6ca9-11e7-8e91-596a1367058d.jpg)

It's okay?

**Comment by zhvn100** [comment]
Hello，i met the same problem . i use arty a7 fpga. The connection between board and the debugger  and  the situation of led of debugger are the same as you. But my error always as follows:
![image](https://user-images.githubusercontent.com/56665570/90233413-b560ee80-de50-11ea-82d3-09da922621ab.png)
So,did you figure it out finally ?  please tell me about it , thank you
