### ISSUE TITLE
why Freedom E300 no date cache?

### ISSUE THREAD

**Issue by Pengnian** [sifive/freedom#33]
Hi  all,

I want to know why Freedom E300 no date cache ? what the purpose this design.

**Comment by mwachs5** [comment]
The E300 is designed for embedded systems, where there isn't usually a large backing store of memory (it has no DDR pins to talk to a large external memory, for example) and where power efficiency is the design goal. To make a lower-power design, we forgo the overhead of hardware caches.

**Comment by Pengnian** [comment]
@mwachs5 Thank you very much
