### ISSUE TITLE
Why does the RISC-V SoC need PCIe FMC?

### ISSUE THREAD

**Issue by clx7913** [sifive/freedom#71]
I am a rookie and have this questions.

The RISC-V SoC could be implemented in FPGA of VC707, doesn't it?Then what's the purpose of PCIe FMC?

**Comment by clx7913** [comment]
Thank you sir.

Another question is that is FMC card  connected to user IO of PL?Can those connection ports be connected by ordinary electrical wires rather than FMC card?

**Comment by jim-wilson** [comment]
I'm not a hardware guy.  You can find a hardware manual at Xilinx for the VC707 board that talks about the FMC connectors.
