### ISSUE TITLE
Would you consider switching to the MIT licence?

### ISSUE THREAD

**Issue by passstab** [sifive/freedom#8]
The Apache license is long and restrictive.  
In particular, Section 4, subsections 2 and 4 both put completely unneeded restraints on the licensee.
It also is incompatible with older versions of the GPL.

Most RISCV projects use MIT.
Please consider choosing a more free license.

Thank you

**Comment by apotheon** [comment]
If you want a patent license, please consider either (disjunctive) dual-license (AL2+MIT) or the [COIL](http://copyfree.org/content/standard/licenses/coil/license.txt).

**Comment by richardxia** [comment]
Sorry, we've made the decision to use the Apache License 2.0 for all of our open source projects and the decision is final.
