### ISSUE TITLE
Make -f Makefile.e300artydevkit mcs fails - module BootRom not found

### ISSUE THREAD

**Issue by charleslucas** [sifive/freedom#96]
New to this, trying to get my arty programmed for the first time.  Running on Ubuntu, have the latest Vivado installed.  I'm failing due to this error:

ERROR: [Synth 8-439] module 'BootROM' not found [/home/cdlucas/github/freedom/builds/e300artydevkit/sifive.freedom.everywhere.e300artydevkit.E300ArtyDevKitConfig.v:234961]

(Although I have lots of previous warnings about "unused sequential elements being removed" and "all elements are unconnected")

I didn't see anything in the readme or Arty Getting Started Guide about configuring a bootrom image location.  I've tried both downloading the RISC-V tools and compiling the toolchain, and pointing the $RISCV environment variable to both.  Am I missing a build step, or need to download bootrom code into Vivado (like the board files?)

Setting these environment variables:
export RISCV="/home/cdlucas/github/freedom-e-sdk/work/build/riscv-gnu-toolchain/riscv64-unknown-elf"
export RISCV_PATH="/home/cdlucas/github/freedom-e-sdk/work/build/riscv-gnu-toolchain/riscv64-unknown-elf"
export RISCV_OPENOCD_PATH="/home/cdlucas/github/freedom-e-sdk/openocd"

Thank you,
-Charles

**Comment by jackkoenig** [comment]
Glad you were able to figure it out!
