### ISSUE TITLE
Outdated RISC-V software toolchain download URL in README.md

### ISSUE THREAD

**Issue by liuqun** [sifive/freedom#99]
https://github.com/sifive/freedom/blob/3624efff1819e52cec30c72f9085158189f8b53f/README.md#L29-L33

The web page `https://www.sifive.com/products/tools/` leads to redirected page of https://www.sifive.com/core-designer/ .

However, https://www.sifive.com/boards seems to be better?

**Comment by richardxia** [comment]
Thanks for reporting the issue, and sorry for the delayed reply. Yes, https://www.sifive.com/boards would be a better location to redirect to. I can update this ticket once we update the redirect.

**Comment by richardxia** [comment]
The redirect has been updated.
